version: '{build}'
skip_tags: true
image: Visual Studio 2019
init:
  - ps: if (0) { iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1')) } #rdp debug
#environment:
#  SEVENZIP_VERSION: 1805
#  CURL_VERSION: 7.62.0
 
build_script:
# work around until appveyor installs nsis
  - choco install nsis.install
  
# work around for curl (get from craftwar.obs_updater_VS2017_curl.zip)  
#  - if exist 7z%SEVENZIP_VERSION%-extra.7z (curl -kLO https://www.7-zip.org/a/7z%SEVENZIP_VERSION%-extra.7z -f --retry 5 -z 7z%SEVENZIP_VERSION%-extra.7z) else (curl -kLO https://www.7-zip.org/a/7z%SEVENZIP_VERSION%-extra.7z -f --retry 5 -C -)
#  - 7z x 7z%SEVENZIP_VERSION%-extra.7z -o7z-extra
#  - curl -kLO https://github.com/craftwar/obs-updater/releases/download/git/craftwar.obs_updater_VS2017_curl.zip -f --retry 5
#  - 7z x craftwar.obs_updater_VS2017_curl.zip
#  - cd craftwar.obs_updater
#  - mklink /H curl.exe ..\curl.exe

  - set VCPKG_LINKER_FLAGS=/LTCG
  - set VCPKG_C_FLAGS=/Gw /Gy /GL /GS- /Zc:__cplusplus
  - set VCPKG_CXX_FLAGS=%VCPKG_C_FLAGS%
#[install vcpkg]
  - cd C:\Tools
  - cmd /c git clone https://github.com/Microsoft/vcpkg
  - .\vcpkg\bootstrap-vcpkg.bat
  - set path=C:\Tools\vcpkg;%path%
  - cd %appveyor_build_folder%
#[/install vcpkg]
  - '"C:\Program Files\Git\usr\bin\sed.exe" -i "s/CRT_LINKAGE static/CRT_LINKAGE dynamic/" /c/tools/vcpkg/triplets/x64-windows-static.cmake' #patch to dynamic crt
  - vcpkg install curl[tool,winssl]:x64-windows-static
  - cd craftwar.obs_updater
  - mklink /H curl.exe C:\Tools\vcpkg\installed\x64-windows-static\tools\curl\curl.exe
#  - mklink /H 7za.exe "%APPVEYOR_BUILD_FOLDER%\7z-extra\x64\7za.exe"
# remove curl, support Win10 1803 later only
#  - mklink /H curl.exe C:\Tools\curl\bin\curl.exe
# use system curl, does it work on win7?
#  - mklink /H curl.exe C:\Windows\System32\curl.exe
  - mklink /H 7z.exe "C:\Program Files\7-Zip\7z.exe"
  - mklink /H 7z.dll "C:\Program Files\7-Zip\7z.dll"
  - 7z a "%APPVEYOR_BUILD_FOLDER%\craftwar.obs_updater.zip" -mx=9 -mpass=15 -mcu=on * -x!0_createZip.cmd -x!obs-studio.ico
  - cd ..
  - call installer\get-vc-ver.cmd
  - '"C:\Program Files (x86)\NSIS\Bin\makensis" /NOCD /NOCONFIG /INPUTCHARSET UTF8 /DVC_redist_ver=%VC_redist_ver% installer\installer.nsi'
artifacts:
- path: craftwar.obs_updater.zip
- path: 'craftwar OBS installer.exe'

deploy:
  - provider: GitHub
    tag: git
#    description: $(APPVEYOR_REPO_COMMIT)
    auth_token:
      secure: KxeGOEgx0+XWdjLWDsyhC+B/w3m8zpvtVY/e+90lCLZgd/2VSuraPZDxdIPB5rfY
    force_update: true
    on:
      branch: master

test: off

#cache:
#  - C:\tools\vcpkg\installed\ -> appveyor.yml
#cache:
#  - '7z%SEVENZIP_VERSION%-extra.7z'

#notifications:
#  - provider: Webhook
#    url:
#      secure: k1kpaz4CB5Rg5a3MTb4XKnd76fJ+9ozz5RACVnNjdgmAjA1OSssZ6LZ3g0NGfzc/
#    headers:
#      Authorization:
#        secure: A0PBwpHtsYzBOuye1EeS0fl562T0NZEInwZp0ZVER1wLQSeE6gzWGrRo2a0E7hii
